### ISSUE TITLE
Missing spells

### ISSUE THREAD

**Issue by oganm** [ephe/grimoire#103]
I noticed many missing spells in the list. Is there a reason why they weren't added? Will you be accepting pull requests if others happened to add them?

**Comment by jayrab** [comment]
the maker of the grimoire, ephe, started this when he had a 5e campaign going and is no longer apart of that so there isnt as big of a push as there once was, he still accepts github pushes for spells they are just not a high priority.

**Comment by ephe** [comment]
As per the README, the Grimoire is still a work-in-progress. I haven't been adding new spells myself because of RL issues (and, as jayrab mentioned, I'm no longer playing 5e), but will always be happy to add spells or take revisions (for example, if something is missing or misspelled). The more help the merrier!

**Comment by Snizzle** [comment]
Currently working on some spell details but I still need to figure out github a little bit.

**Comment by jayrab** [comment]
Feel free to add me on steam and I can help walk you through anything, snizzle

**Comment by Snizzle** [comment]
Thanks for the offer. I will contact you if I have any questions.
Just now finished all the missing spells up to Freedom of Movement.

**Comment by gc3** [comment]
I'm also happy to add the rest of what's in the PHB assuming the couple of smaller pull requests I made were of the right format, and I know they'll be accepted at some point.

**Comment by gc3** [comment]
BTW, I got bored of waiting and just finished this.

http://gc3.github.io/grimoire/

**Comment by ephe** [comment]
Hah, fair enough :P I'll review this and push an updated build sometime tonight, but I don't mind the fork.

**Comment by jayrab** [comment]
While ephe has had things come up in the past that has prevented them from updating the grimoire, we all have been there (atlease my team) were real life has come up but they have always been diligent about checking all of our edits and uploading them if correct when they have had the time. 

In that regard the +3 people including myself will stay with ephe's branch so I do hope now that ephe is back that you will resume adding to it. As a side note though it may be better to send single spells then the full library, both because it becomes daunting for ephe to review therefore unlikely that he will have the time and that making corrections is easier then rejecting the whole batch for one error.

**Comment by gc3** [comment]
Sorry if I wasn't clear. I wasn't trying to usurp the project. I made a pull request for my work before I published it for my own use.

**Comment by gc3** [comment]
@ephe Thank you so much for getting to this :)

**Comment by ephe** [comment]
@gc3 No problem, and thank you for helping out so much! I've got a build up now with those spells (and the start of some internal linking), but of course you are absolutely welcome to keep a fork of the project as well and tinker as you will. This is, after all, github ;)
